apiVersion: v1
data:
  jcasc-default-config.yaml: "jenkins:\n  authorizationStrategy:\n    loggedInUsersCanDoAnything:\n\
    \      allowAnonymousRead: false\n  securityRealm:\n    local:\n      allowsSignup:\
    \ false\n      enableCaptcha: false\n      users:\n      - id: \"${chart-admin-username}\"\
    \n        name: \"Jenkins Admin\"\n        password: \"${chart-admin-password}\"\
    \n  disableRememberMe: false\n  mode: NORMAL\n  numExecutors: 0\n  labelString:\
    \ \"\"\n  projectNamingStrategy: \"standard\"\n  markupFormatter:\n    plainText\n\
    \  clouds:\n  - kubernetes:\n      containerCapStr: \"10\"\n      defaultsProviderTemplate:\
    \ \"\"\n      connectTimeout: \"5\"\n      readTimeout: \"15\"\n      jenkinsUrl:\
    \ \"http://jenkins.jenkins.svc.cluster.local:8080\"\n      jenkinsTunnel: \"jenkins-agent.jenkins.svc.cluster.local:50000\"\
    \n      skipTlsVerify: false\n      usageRestricted: false\n      maxRequestsPerHostStr:\
    \ \"32\"\n      retentionTimeout: \"5\"\n      waitForPodSec: \"600\"\n      name:\
    \ \"kubernetes\"\n      namespace: \"jenkins\"\n      restrictedPssSecurityContext:\
    \ false\n      serverUrl: \"https://kubernetes.default\"\n      addMasterProxyEnvVars:\
    \ false\n      credentialsId: \"\"\n      podLabels:\n      - key: \"jenkins/jenkins-jenkins-agent\"\
    \n        value: \"true\"\n      templates:\n        - name: \"default\"\n   \
    \       namespace: \"jenkins\"\n          id: 95d21559f6381190c43a9aa24e40c4b09348e5a043c03a5d3e59615d2435de79\n\
    \          containers:\n          - name: \"jnlp\"\n            alwaysPullImage:\
    \ false\n            args: \"^${computer.jnlpmac} ^${computer.name}\"\n      \
    \      envVars:\n              - envVar:\n                  key: \"JENKINS_URL\"\
    \n                  value: \"http://jenkins.jenkins.svc.cluster.local:8080/\"\n\
    \            image: \"jenkins/inbound-agent:3385.vf1123fb_515da_-1\"\n       \
    \     privileged: \"false\"\n            resourceLimitCpu: 512m\n            resourceLimitMemory:\
    \ 512Mi\n            resourceRequestCpu: 512m\n            resourceRequestMemory:\
    \ 512Mi\n            ttyEnabled: false\n            workingDir: /home/jenkins/agent\n\
    \          idleMinutes: 0\n          instanceCap: 2147483647\n          label:\
    \ \"jenkins-jenkins-agent \"\n          nodeUsageMode: \"NORMAL\"\n          podRetention:\
    \ Never\n          showRawYaml: true\n          serviceAccount: \"default\"\n\
    \          slaveConnectTimeoutStr: \"100\"\n          yamlMergeStrategy: override\n\
    \          inheritYamlMergeStrategy: false\n  slaveAgentPort: 50000\nsecurity:\n\
    \  apiToken:\n    creationOfLegacyTokenEnabled: false\n    tokenGenerationOnCreationEnabled:\
    \ false\n    usageStatisticsEnabled: true\nunclassified:\n  location:\n    url:\
    \ https://jenkins.rgrishabh.in/"
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/component: jenkins-controller
    app.kubernetes.io/instance: jenkins
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: jenkins
    helm.sh/chart: jenkins-5.9.64
    jenkins-jenkins-config: 'true'
  name: jenkins-jenkins-jcasc-config
  namespace: jenkins

