apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/component: jenkins-controller
    app.kubernetes.io/instance: jenkins
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: jenkins
    helm.sh/chart: jenkins-5.9.64
  name: jenkins-agent
  namespace: jenkins
spec:
  clusterIP: 10.98.96.127
  clusterIPs:
  - 10.98.96.127
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: agent-listener
    port: 50000
    protocol: TCP
    targetPort: 50000
  selector:
    app.kubernetes.io/component: jenkins-controller
    app.kubernetes.io/instance: jenkins
  sessionAffinity: None
  type: ClusterIP

